[functions]
  node_bundler = "esbuild"

[functions."snapshot_avis"]
  schedule = "0 3 */2 * *"

[functions."snapshot_rank"]
  schedule = "50 6 * * 1"

[functions."snapshot_rank_b"]
  schedule = "53 6 * * 1"

[functions."snapshot_rank_c"]
  schedule = "56 6 * * 1"

[functions."snapshot_rank_d"]
  schedule = "59 6 * * 1"
